### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by Prajwal-Koirala** [Nyr/wireguard-install#1]
hey can u add my script on this as well, it seems like ur installing the gpg keys manually i think my script might be better for some users.

https://github.com/complexorganizations/wireguard-manager

**Comment by Nyr** [comment]
I'm not sure about what you exactly want me to do, can you please clarify? If you want to use any part of my work: yes you can, as long as the terms of the license are respected.

Or are you requesting some kind of modification on my end?

And speaking of copyright: it looks like your work is based on two different third party forks which in turn were based on my original work. So please, make sure that you are respecting the copyright.
