### ISSUE TITLE
Conflict with Your openvpn install

### ISSUE THREAD

**Issue by Voha888** [Nyr/wireguard-install#100]
I installed both Your scripts on same ubuntu VPS: for openvpn, and for wireguard. I need both ptotocols. And now, after reboot I have only one working server. When openvpn works - wireguard not works. I rebbot VPS second time, now wireguard works, and openvpn not works

**Comment by Nathan9745354** [comment]
Could you provide more details?
That sound not make sense , they are using different gateway and port , shouldn't be conflict.

**Comment by Nyr** [comment]
This is very likely to be a configuration problem in your side, not with the installer.
