### ISSUE TITLE
End-End Encryption

### ISSUE THREAD

**Issue by red0888** [Nyr/wireguard-install#102]
Procustodibus has created a guide to set up end-end encrypted wireguard tunnel in the traditional hub and spoke architecture using nested tunnels.

I request that the script include an option to create an end-end encrypted tunnels.

https://www.procustodibus.com/blog/2021/12/wireguard-e2ee-hub-and-spoke/

**Comment by KaeTuuN** [comment]
Since this needs multiple Configuration on the host site, I don't think, this will be implented in this server side script.
But feel free to make a working Pull Request.

**Comment by Valdes11** [comment]
hello there thanks for the answer but for sure i did it

**Comment by Valdes11** [comment]
would you like i give my user pass u trying ?

**Comment by sunapi386** [comment]
@red0888 Using this branch https://github.com/Nyr/wireguard-install/pull/108/files which allows you to select your own dns and network, so you can just configure another VPN inside the first VPN. Have one of the clients be a server in this e2ee.

**Comment by Nyr** [comment]
That is out of the scope of this project.
