### ISSUE TITLE
"invalid selection" when using DDNS URL

### ISSUE THREAD

**Issue by KylerianHD** [Nyr/wireguard-install#104]
Hi.

I have the following problem:
I want to configure Wireguard ipv4 in this script with my DDNS URL shown in the screenshot of the console. (vpn.kylerianhd-private.cc)
The problem I have now is, that it says: "invalid selection".
Why is that the case and how can I configure it with my DDNS URL?

Here is some additional information. :
As DDNS service I use Cloudflare with DDClient (https://github.com/ddclient/ddclient).
This DDNS Record is changed to my public IP every time my public IP changes.
PortForwarding is active for Wireguard and it's Port 51820 (which shouldn't affect this script but mention it anyways if this piece of information is needed).
Also, as it can be seen in the screenshot of my Cloudflare DNS Records, the DDNS subdomain is proxied.
How to use this script for this purpose is shown in this video: https://youtu.be/rtUl7BfCNMY. But It seems that it is a little outdated and the dude runs his Server behind a NAT (which I don't really know if it severely changes anything in this script or at least its behaviour).
Currently running all this on my RaspberryPI 4B (8GB RAM).

Console Screenshot:
<img width="438" alt="Console Screenshot" src="https://user-images.githubusercontent.com/66698817/206013892-1400d5db-31a3-442b-bda2-8762748df33a.png">

Cloudflare Screenshot:
<img width="789" alt="Cloudflare Screenshot" src="https://user-images.githubusercontent.com/66698817/206018403-35d7feb1-e788-497c-825d-94c5259ff8db.png">

It would be nice if you could help me.
Until then I wish you a nice day.

~KylerianHD

**Comment by KylerianHD** [comment]
Thanks for your answer @KaeTuuN.
I'll try and edit the script to make it less annoying to create an automatic Wireguard config if I need it again. ;)

However, I'm not a good bash scripter myself (currently learning to create bash scripts), so if you could give me a push in the right direction I would heavily appreciate it.
It would be nice to leave it all as is and add the FQDN functionality.
This probably means that I would have to make a new variable and function and check if the input has the correct syntax given by the user. Would I have to do it that way (is this at least easier to implement) or could I implement it in the lines 189 to 202 combined with the already existing check? The last method I described is what I would prefer but if there is an easier way to do this then I would prefer this instead of course.

Thanks again for your help! :)

**Comment by KaeTuuN** [comment]
If you want a clean implementation I recommend to copy and paste the mentioned lines and Edit them to accept an FQDN. After that you should implement a new If statement  like "Do you want to use your IP or FQDN for Wireguard?" If IP is selected it jumps to the already implemented code and if FQDN is selected it would enter your new path.

And if you get it working you might create a merge request and maybe @Nyr will expand the script with your function. ;-)
