### ISSUE TITLE
Users files

### ISSUE THREAD

**Issue by yshinkarev** [Nyr/wireguard-install#105]
I added a new user. Then I removed same user. User file is still located in /root directory. Seems, it could be deleted on remove user.

Can I reuse users configurations after reinstall wireguard?
For example. I install wireguard and add a lot of users. These users is used at my laptops, smartphones and etc.
I keep all my configuration files.
Now I want to reinstall wireguard or use another server. But I want keep my users. Can I do it?

**Comment by Nyr** [comment]
> Seems, it could be deleted on remove user.

I prefer for the process to be non-destructive. What if the admin renamed a configuration file, and it no longer matches the original user name? Edge case, I know, but why risk it.

> Can I reuse users configurations after reinstall wireguard?

If you migrate all the configuration, yes.
