### ISSUE TITLE
ipv6 subnet not created

### ISSUE THREAD

**Issue by POMATu** [Nyr/wireguard-install#11]
Hi, I see only ipv4 subnet in interface section of server config

is it some detection or something?

have to add ipv6 subnet manually

**Comment by MasterGroosha** [comment]
@POMATu How did you fix it?

@Nyr for some reason, `ip -6 addr | grep -c 'inet6 [23]'` command returns 0 as if there weren't any IPv6 adapters. However `ip -6 addr | grep -c 'inet6'` returns 12 (the correct number)

**Comment by POMATu** [comment]
@MasterGroosha I just appended ipv6 ips manually to each client in wg0.conf and also to each client certs. Have to do it manually each time

wg0.conf
```
[Interface]
Address = 10.7.0.1/24, fc00:1:1::1/128

# BEGIN_PEER client
[Peer]
AllowedIPs = 10.7.0.2/32, fc00:1:1::2/128
# END_PEER client
```
and so on but I think the problem might be related to not having ipv6 prefix on main network interface facing internet. I just needed local ipv6 subnet so looks like installer automatically detected not having ipv6 prefix on internet interface and ignored ipv6 in configuration completely

**Comment by Nyr** [comment]
Detection is simple: IPv6 addresses starting with `2` or `3` on the `inet 6` interface are detected.

What kind of IPv6 addresses is OVH assigning you for internet access? Looking at the output of `ip -6 addr` would help me understand (you can censor the second half of the IPv6 addresses if you wish).

Other IPv6 addresses including internal, are not detected.

**Comment by MasterGroosha** [comment]
@Nyr 
```
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 2001:41d0:502:2200::abcd/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::f816:5afb:abdd:abcd/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by Nyr** [comment]
@MasterGroosha passing that output to `grep -c 'inet6 [23]'` returns `1` as expected.

**Comment by MasterGroosha** [comment]
@Nyr you're right. My bad. For some reason, OVH didn't enable IPv6 support by default and I was getting only link-local (`fe80:....`) address, that's why your script told me there is no IPv6.
I've re-checked your script after enabling "real" IPv6 and it works fine.
