### ISSUE TITLE
Would like to be able to specify server's IP Addresses so multiple server/clients can be setup. 

### ISSUE THREAD

**Issue by jacksnodgrass** [Nyr/wireguard-install#113]
I have two servers. If I run the setup script, it sets up a 10.77.0.0/16 network... but I need two different networks so I can have a client connect to both servers.  I had to go in and change all occurences of 10.7 in the wireguard-install.sh to 10.8 so that my client could connect to both of my servers.... 10.7.0.1 and 10.8.0.1. It would be nice if I didn't have to change 10.7 to 10.8 in the code.

**Comment by Nyr** [comment]
This is no planned, sorry.

**Comment by hwcltjn** [comment]
@Nyr Would you accept a PR for this feature?
I'm thinking a simple prompt when the script is run in order to specify a custom subnet.
