### ISSUE TITLE
Add option to use wireguard-go implementation.

### ISSUE THREAD

**Issue by nixigaj** [Nyr/wireguard-install#117]
Tailscale has made some [improvements](https://tailscale.com/blog/more-throughput/) to the official WireGuard Go implementation atop the Linux kernel, with it having the potential of outperforming the kernel driver.

Would it be possible to let the user explicitly choose wireguard-go over BoringTun or the kernel driver?

**Comment by Nyr** [comment]
Are the proposed improvements supported in the current kernels of all supported distros? Is this already available upstream in wireguard-go?

We could start to consider this at that point, but it seems like we are not there yet (I just took a quick look so correct me if I am wrong).

Anyway this would be used only for when we need an userspace implementation. The kernel implementation is good enough and cleaner.
