### ISSUE TITLE
Support dual-stack servers

### ISSUE THREAD

**Issue by sindastra** [Nyr/wireguard-install#121]
It seems connecting through IPv4 works fine, and I get both an external IPv4 and IPv6 when using the tunnel.

However, replacing the endpoint in the config with the server's IPv6 address does not work (I made sure the port is open for both IPv4 and IPv6).

Any ideas?

**Comment by Nyr** [comment]
Support for this is not planned. Connections over IPv4 are often more reliable, so at the moment the script does not support tunneling over IPv6. Also for other legacy compatibility reasons.

**Comment by sindastra** [comment]
> Connections over IPv4 are often more reliable

What makes you say that?
