### ISSUE TITLE
TUN device unavailable

### ISSUE THREAD

**Issue by tekgamerpt** [Nyr/wireguard-install#122]
Cant install script on Proxmox 8, using containers... tried with debian and also ubuntu

The system does not have the TUN device available.
TUN needs to be enabled before running this installer.

Already tried several hints on foruns but still not working....
Any clue?

Thank you

**Comment by KaeTuuN** [comment]
My crystal ball says you havn't tested tried this advice: Comment out the DNS Server in the generated config File.

**Comment by Bigmanekb** [comment]
you can use this method:

`nano /usr/sbin/tunscript.sh
`
add there:
```
#!/bin/bash
mkdir /dev/net
mknod /dev/net/tun c 10 200
chmod 0666 /dev/net/tun
```
Save
`chmod +x /usr/sbin/tunscript.sh`

`nano /etc/rc.local `

insert before exit 0:
`/usr/sbin/tunscript.sh || exit 1`

Save file
`sh /usr/sbin/tunscript.sh`

Thats all
