### ISSUE TITLE
Wireguard behind CGNAT

### ISSUE THREAD

**Issue by drtiwarir** [Nyr/wireguard-install#123]
I am very thankful to Nyr for making 1 click wireguard server installation.
I used it to watch streaming videos/movies/sports from India, but recently Indian websites have blocked all data centre IP addresses.
I have a old pc with Ubuntu at my home and want to install wireguard server on it, but my home broadband is behind CGNAT.
I have searched on github and tried but no good results.
Nyr can you help with a 1 click script for VPS (data centre) and 1 click script for home PC (behind CGNAT) ?

Kind regards

**Comment by Albonycal** [comment]
Check out https://tailscale.com/
easy to deploy mesh VPN :D

**Comment by Albonycal** [comment]
you don't have to do anything, tailscale does it for you. 
check out their website

**Comment by drtiwarir** [comment]
Thanks
