### ISSUE TITLE
Wireguard behind NAT or on IPv6

### ISSUE THREAD

**Issue by stpnwf** [Nyr/wireguard-install#125]
Hi, I am behind a CGNAT (so my portforwards don't work :/ ) and I would like to get Wireguard working. I saw you suggested in #123 that Tailscale be used instead. But sadly Tailscale doesn't really work for my needs. I couldn't use 192.168 addresses there, so the experience from being on Tailscale and on my home network wasn't seamless on my services. I had to manually keep changing 192 addresses to Tailscale addresses. Also I plan to allow some friends access to my VPN to access my servers and I would prefer to do it with Wireguard.

I am also in talks with my ISP to see if I can get taken out of the NAT and given a "real" IPv4 address. But other than that, is there anything else I can do?

I saw in some issues that you say most ISPs IPv6 implementations are broken, is it possible to set up Wireguard on IPv6? Or bc of that it isn't?

Sorry if I am asking dumb questions. This is all kinda new to me, so I am learning as I go. Thanks in advance

**Comment by Nyr** [comment]
If you can not get a port forwarded, hosting a normal WireGuard server behind NAT is not viable.
