### ISSUE TITLE
I can't customize my public IP address

### ISSUE THREAD

**Issue by fengwenhao-hyyd** [Nyr/wireguard-install#128]
I use a vps as server to install wireguard, in the first step, wireguard-install script show a couple of ip address, like that
> Welcome to this WireGuard road warrior installer!
> 
> Which IPv4 address should be used?
>      1) 10.0.0.12
>      2) 172.24.0.1
>      3) 172.17.0.1
>      4) 192.168.0.1
>      5) 192.168.112.1
>      6) 192.168.176.1
> IPv4 address [1]:

but my public ip address not in it, i try to type my public ip in, but error "invalid selection" occurred

my vps is form Tencent Cloud, it seems can't get public ip with ifconfig, maybe that is the reason my public ip not in the select list.
can i customize my public ip?

**Comment by Nyr** [comment]
Very likely your VPS is behind NAT. I am not sure about the networking since I do not use Tencent Cloud. Ask them.
