### ISSUE TITLE
Feature request: Reprint QR code for existing account.

### ISSUE THREAD

**Issue by ufufufu** [Nyr/wireguard-install#13]
Hello,

Is it possible to have a feature where I can reprint the QR code for an existing account that have already been created in the server? After all, copy-and-paste to a smartphone from a computer is not really trivial.

Proposed workflow

1. Run `wget https://git.io/wireguard -O wireguard-install.sh && bash wireguard-install.sh` on bash.
2. Select "Print QR code" option.
3. Select account whose QR code I want to scan.
4. QR code appears.
5. I scan QR code via wireguard client on smartphone.

Thanks.

**Comment by drphr4ud** [comment]
Can't you just do

`qrencode -t ansiutf8 < _client.conf_` in the shell ?

where _client.conf_ is the config file for the client you want to reprint.

**Comment by Nyr** [comment]
Yeah, for the time being, just run the command manually. Thanks @drphr4ud.
