### ISSUE TITLE
Public IPv4 address step is skipped.

### ISSUE THREAD

**Issue by zachvlat** [Nyr/wireguard-install#134]
It may sound weird but  the Public IPv4 address input, is totally skipped and as a result the qr code and the .conf file that is generated doesn't have the address before the port. It's empty. I think because of that the conf file is completely wrong, even if I edit the file and put my address url. I was using it for a long time and now I have this issue.

**Comment by Nyr** [comment]
Are you using a server which is behind NAT? That is the only time when you are asked for a public IPv4 address.

Please, provide the output of `ip -4 addr` and do not censor it too much.

**Comment by zachvlat** [comment]
Yes, I am behind a NAT, but why skips the part that I 'm putting the url from freedns? Also forgot to add this screenshot if it helps...
![Screenshot_20231119_220234](https://github.com/Nyr/wireguard-install/assets/28532979/2eff863c-108d-4c6b-9f70-a5449568e45d)

**Comment by Nyr** [comment]
Please, provide the full installation log, not just a screenshot. And the output of the command I requested.

**Comment by zachvlat** [comment]
it worked. I uninstalled it and start from the beginning and now it works fine... I may missed something. Thank you for the quick response though!
