### ISSUE TITLE
windows browsers not working

### ISSUE THREAD

**Issue by gghkp** [Nyr/wireguard-install#137]
Hello, I appreciate your valuable script, I installed wireguard in my ubuntu server, and everything works fine in andriod phones, but my browsers in Windows don't work with wireguard, while windows apps like Telegram etc work fine in Windows, Please help me.

**Comment by Nyr** [comment]
This is not an issue with the script, check maybe the browser's DNS configuration or try browsing to https://1.1.1.1 but I can not offer further help.
