### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by vuh95** [Nyr/wireguard-install#138]
Hello.

I am trying to use this script to install a Wire Guard on a Ubuntu Oracle instance, and I am getting this issue.

<img width="932" alt="image" src="https://github.com/Nyr/wireguard-install/assets/60206812/6aa8f854-cde9-4d3a-a8da-b970919c543e">

Can anyone help me resolve this issue?
Thank you.

**Comment by KaeTuuN** [comment]
You do not need to run wget as root (You should never do that) but instead run bash as root.

**Wrong:** sudo wget [...] && bash [...]
**Correct:** wget [...] && sudo bash [...]

**Comment by Nyr** [comment]
Thanks @KaeTuuN for the detailed explanation.

**Comment by KaeTuuN** [comment]
@Nyr Maybe you could add sudo to the Install string in README.md?

**Comment by Nyr** [comment]
No, as it depends on the particular environment. Plenty of VPS providers provide root accounts by default.

**Comment by vuh95** [comment]
> You do not need to run wget as root (You should never do that) but instead run bash as root.
> 
> **Wrong:** `sudo wget [...] && bash [...]` **Correct:** `wget [...] && sudo bash [...]`
> 
> Further Explanation: You run two separate commands and concat them with `&&` so `sudo` is not used for the whole line, but only for next command. Your `&&` does run the right command only if the left command returns `0` or `true`. More Explanation: https://stackoverflow.com/questions/4510640/what-is-the-purpose-of-in-a-shell-command

Thank you so much for your kind response.
I can run the script now.
