### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by dkon-de** [Nyr/wireguard-install#139]
Whenever I am running your script, I get the following error:
`Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8003::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443... failed: Connection timed out.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... `

That's it.

**Comment by Nyr** [comment]
Your server is having issues connecting to `raw.githubusercontent.com`.

This is not an issue with the script and will be likely resolved soon.
