### ISSUE TITLE
No internet access "sometimes" after wireguard installation

### ISSUE THREAD

**Issue by brlndtech** [Nyr/wireguard-install#14]
Hello, I have setup wireguard with your beautiful script 

it's works ! I can connect to my server from LTE but I can't reach internet 

I have also check if the ip forwading was activated with  ```echo 1 > /proc/sys/net/ipv4/ip_forward```

do you have an issue to solve my problem ? 

thank's 

brlndtech

(Debian 10.X)

**Comment by aaronstuder** [comment]
I am having the same issue with Debian 10

**Comment by aaronstuder** [comment]
Same issue on Ubuntu 18.04

**Comment by aaronstuder** [comment]
I am able to ping the client from the server, so it is connecting. My something is wrong with DNS?

**Comment by brlndtech** [comment]
> I am able to ping the client from the server, so it is connecting. Maybe something is wrong with DNS?

No, I have tested to ping 8.8.8.8, and I can't access to it...

**Comment by z3ro-dot-z3ro** [comment]
I think this is a kernel issue.  I had the problem with one VPS host that used a newer kernel, but no on another that uses an older one.  There doesn't seem to be much guidance or information either way, though.

**Comment by Nyr** [comment]
Probably not a kernel issue.

Is your server behind NAT? Can you try from a non-LTE client?

Is your server a dedicated or fully virtualized system, or is it a container like OpenVZ or LXC?

**Comment by brlndtech** [comment]
> Probably not a kernel issue.
> 
> Is your server behind NAT? Can you try from a non-LTE client?
> 
> Is your server a dedicated or fully virtualized system, or is it a container like OpenVZ or LXC?
> 
> Specify "sometimes": when does it work? When it doesn't?

Yes, my server is behind a nat, I have already try with a wifi connexion outside of my home 
 
My server is a fully dedicated system.  it's not a virtual server. 

When I install wireguard at the first, it's works, but when I reboot the server, I can connect to the VPN but not to Internet unfortunatly.

**Comment by Nyr** [comment]
@brlndtech if the server IP is dynamic, that can be the problem because `POSTROUTING` rules will still perform `SNAT` to the old IP.

**Comment by brlndtech** [comment]
the ip of the server is FIX.. so I don't think so .. @Nyr
