### ISSUE TITLE
No support for almalinux 8

### ISSUE THREAD

**Issue by bdgreenweb** [Nyr/wireguard-install#142]
Hello,
thanks for making this awesome script. But it's not working in almalinux 8. please make it compatible with almalinux 8.

NAME="AlmaLinux"
VERSION="8.9 (Midnight Oncilla)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.9 (Midnight Oncilla)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

**Comment by Nyr** [comment]
AlmaLinux 8 is no longer supported by the installer.

You can obtain the latest compatible version here:
https://raw.githubusercontent.com/Nyr/wireguard-install/bcc914db95a789e51a84402b057d3116a26fb151/wireguard-install.sh
