### ISSUE TITLE
[REQ] Add Ability to make custom IP Range/CIDR

### ISSUE THREAD

**Issue by Gedrean** [Nyr/wireguard-install#143]
I have two networks I'm attempting to wireguard.  Both use a 10.x class A internal IP scheme.
When I get the client config built with this, it uses 10.7 IP scheme, which could present conflicts if a subnet for 10.7 is taken elsewhere (routing issue).

This script would be awesome if you could change the tunnel's IP scheme to a custom first-3-octets IP scheme (such as 192.168.15.x or whatever the user wishes).

I had a look and it looks like the 10.7 IP scheme is hard-referenced in several places, and could be replaced by a variable insert with only one additional input required at initial setup.

**Comment by Nyr** [comment]
You will need to change this manually.
