### ISSUE TITLE
QR Code does not work

### ISSUE THREAD

**Issue by snailcatcher** [Nyr/wireguard-install#144]
Hi there,

I got the problem, that my QR code doesn't work because my peer endpoint was wrong.
After looking inside the script I found the reason for that.
https://github.com/Nyr/wireguard-install/blob/8e8c483384f88b845ddc0ecbca0253fb5e4cf973/wireguard-install.sh#L352
This line sets a comment in the wg0.conf file, but each time I create a new peer this will be overwritten and the comment is not present in the configuration anymore.

https://github.com/Nyr/wireguard-install/blob/8e8c483384f88b845ddc0ecbca0253fb5e4cf973/wireguard-install.sh#L178
This line will read out this comment and nothing is there after the first client was added succesfully.

I hope this helps with fixing the issue. I would have done it myself, but cant figure out a good solution for this.
I post this because I hope someone else has a good idea.

I think this is related to https://github.com/Nyr/wireguard-install/issues/89

### Reproduce
1. Install the script (In my case on Debian Bookworm)
2. Add the client that is added with the script via QR code to your device
3. Add a second client
4. Try to add the second client to your device (QR will be rejected by the official wirguard app)

And btw thank you for this great script

**Comment by Nyr** [comment]
Unfortunately I am unable to reproduce your issue.

The `# ENDPOINT` comment is not overwritten after adding a second client, and there is nothing in the referenced code overwriting it.

If you still think that there is something wrong, please provide the broken client configuration file and a screenshot of the generated QR code.
