### ISSUE TITLE
Ubuntu 22.04 or higher is required to use this installer. This version of Ubuntu is too old and unsupported.

### ISSUE THREAD

**Issue by DrewLosing** [Nyr/wireguard-install#146]

**Comment by sskras** [comment]
@Nyr, may I ask for the reason it is not planned?

IMO, Ubuntu 20.04 LTS is a pretty fresh distro. I would try to add the support when I get it on my hands.

**Comment by sskras** [comment]
Wow, that was harsh: https://github.com/Nyr/wireguard-install/commit/b049ab486e1a98cebfbf41a97c26780a8ddca925
Still interested in the motivation.

**Comment by Nyr** [comment]
> Ubuntu 20.04 LTS is a pretty fresh distro

It is not.

It has reached its end of life, it is unmaintained, and as such should not be used.
