### ISSUE TITLE
Connection to VPC on Digitalocean

### ISSUE THREAD

**Issue by skywalker282** [Nyr/wireguard-install#149]
I just installed Wireguard with the script and unfortunately, I cannot reat my VPC's droplets ( servers ). I tested the interconnection on the local network inthe DO infra and they ping each other without any issue.

Would like to know if there could be any config to fix this misbehaviour. I opted for 1.1.1.1 for DNS and left default value for other options of the script. Any help will be appreciated

**Comment by abxyxx** [comment]
I had the same issue with digital ocean, I fixed it by choosing the internal IP instead of public when setting up wireguard. It means the VPN can't access the internet but you can see all the other servers
