### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xxf185** [Nyr/wireguard-install#150]
Reading state information... Done
qrencode is already the newest version (4.0.2-2).
wireguard is already the newest version (1.0.20200513-1~20.04.2).
0 upgraded, 0 newly installed, 0 to remove and 157 not upgraded.
wireguard-install.sh: line 349: /etc/wireguard/wg0.conf: No such file or directory
chmod: cannot access '/etc/wireguard/wg0.conf': No such file or directory
grep: /etc/wireguard/wg0.conf: No such file or directory
grep: /etc/wireguard/wg0.conf: No such file or directory
wireguard-install.sh: line 159: /etc/wireguard/wg0.conf: No such file or directory
grep: /etc/wireguard/wg0.conf: No such file or directory
grep: /etc/wireguard/wg0.conf: No such file or directory
wg: Key is not the correct length or format
grep: /etc/wireguard/wg0.conf: No such file or directory
grep: /etc/wireguard/wg0.conf: No such file or directory
Job for wg-quick@wg0.service failed because the control process exited with error code.

**Comment by Nyr** [comment]
Try installing in a clean OS image.
