### ISSUE TITLE
Speed issues.  

### ISSUE THREAD

**Issue by ZuluImpact** [Nyr/wireguard-install#154]
Hey, You done a great job. it simplifes my work a lot. But. I notice something.  I have using 6GB ram of VPS with 4vCPU core.  at Ubuntu.
When I am using VPS created VPN, my speed is near 20MB/sec and when I am using VPS created VPN, its near 13MB, 
I am not getting, why its slow?

Can you give me some hints?

**Comment by Nyr** [comment]
There are many factors which can affect this, but the mentioned speed is kind of normal over the internet.
