### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by gghkp** [Nyr/wireguard-install#157]
Hello it's me again and I had a couple of questions:
1- How do I properly backup my wireguard  Users in this script ?
2- How many users can I add in this script ?
Thanks in advance

**Comment by KaeTuuN** [comment]
1. Simply backup your Wireguard config for Client and Server. (Debian server default: /etc/wireguard/wg0.conf )
2. It's a /24 Subnet. That means, 253 Clients, 1 Server, 1 Broadcast.
