### ISSUE TITLE
It connects, But sometimes It doesn't work

### ISSUE THREAD

**Issue by Mushebeq** [Nyr/wireguard-install#19]
I installed wireguard on my hetzner vps, But my ping is pretty bad. I tried by reinstalling and changing vps but i got same issue. is there anyway to debug? 

```
Pinging 168.119.114.211 with 32 bytes of data:
Reply from 168.119.114.211: bytes=32 time=192ms TTL=64
Reply from 168.119.114.211: bytes=32 time=117ms TTL=64
Request timed out.
Request timed out.
Request timed out.
Reply from 168.119.114.211: bytes=32 time=215ms TTL=64
Request timed out.
Request timed out.
Request timed out.
Reply from 168.119.114.211: bytes=32 time=116ms TTL=64
Request timed out.
Request timed out.
Reply from 168.119.114.211: bytes=32 time=237ms TTL=64
Request timed out.
Reply from 168.119.114.211: bytes=32 time=180ms TTL=64
Request timed out.
Reply from 168.119.114.211: bytes=32 time=116ms TTL=64
Request timed out.
Reply from 168.119.114.211: bytes=32 time=117ms TTL=64
Reply from 168.119.114.211: bytes=32 time=184ms TTL=64
Reply from 168.119.114.211: bytes=32 time=178ms TTL=64
Reply from 168.119.114.211: bytes=32 time=117ms TTL=64
Reply from 168.119.114.211: bytes=32 time=118ms TTL=64
Reply from 168.119.114.211: bytes=32 time=184ms TTL=64
Reply from 168.119.114.211: bytes=32 time=117ms TTL=64
Reply from 168.119.114.211: bytes=32 time=117ms TTL=64
Reply from 168.119.114.211: bytes=32 time=134ms TTL=64
Request timed out.
Reply from 168.119.114.211: bytes=32 time=117ms TTL=64
Reply from 168.119.114.211: bytes=32 time=172ms TTL=64
Request timed out.
Request timed out.
```

**Comment by Mushebeq** [comment]
Sometimes it doesn't even work at all, It connects, But no internet connection!

**Comment by Nyr** [comment]
Seems like you have lots of packet loss, this is a connectivity problem and doesn't have anything to do with the WireGuard installer.

**Comment by Mushebeq** [comment]
@Nyr This is my ping without vpn

Pinging 8.8.8.8 with 32 bytes of data:
Reply from 8.8.8.8: bytes=32 time=204ms TTL=114
Reply from 8.8.8.8: bytes=32 time=131ms TTL=114
Reply from 8.8.8.8: bytes=32 time=128ms TTL=114
Reply from 8.8.8.8: bytes=32 time=130ms TTL=114
Reply from 8.8.8.8: bytes=32 time=130ms TTL=114
Reply from 8.8.8.8: bytes=32 time=129ms TTL=114
Reply from 8.8.8.8: bytes=32 time=128ms TTL=114
Reply from 8.8.8.8: bytes=32 time=129ms TTL=114
Reply from 8.8.8.8: bytes=32 time=134ms TTL=114
Reply from 8.8.8.8: bytes=32 time=130ms TTL=114
Reply from 8.8.8.8: bytes=32 time=128ms TTL=114
Reply from 8.8.8.8: bytes=32 time=128ms TTL=114
Reply from 8.8.8.8: bytes=32 time=129ms TTL=114
Reply from 8.8.8.8: bytes=32 time=127ms TTL=114
Reply from 8.8.8.8: bytes=32 time=128ms TTL=114
Reply from 8.8.8.8: bytes=32 time=130ms TTL=114
Reply from 8.8.8.8: bytes=32 time=151ms TTL=114
Reply from 8.8.8.8: bytes=32 time=129ms TTL=114
Reply from 8.8.8.8: bytes=32 time=128ms TTL=114
Reply from 8.8.8.8: bytes=32 time=130ms TTL=114
Reply from 8.8.8.8: bytes=32 time=136ms TTL=114
Reply from 8.8.8.8: bytes=32 time=142ms TTL=114
Reply from 8.8.8.8: bytes=32 time=169ms TTL=114
Reply from 8.8.8.8: bytes=32 time=138ms TTL=114
Reply from 8.8.8.8: bytes=32 time=134ms TTL=114
Reply from 8.8.8.8: bytes=32 time=129ms TTL=114
Reply from 8.8.8.8: bytes=32 time=134ms TTL=114

Ping statistics for 8.8.8.8:
    Packets: Sent = 27, Received = 27, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 127ms, Maximum = 204ms, Average = 135ms
Control-C
^C

**Comment by Nyr** [comment]
This is clearly a connectivity issue. Maybe try a VPN server closer to your location.

**Comment by Mushebeq** [comment]
Sorry but the above result was from vpn. My connection is stable and if i didn't use vpn i get 20ms ping. I tried the vpn on my windows server, but i got the same issue
