### ISSUE TITLE
Can't access Google website via Google Cloud Platform

### ISSUE THREAD

**Issue by adahbingee** [Nyr/wireguard-install#22]
Install bash with GCP Compute Engine VM (f1 micro server, 1CPU + 600MB RAM)

* Opened UDP and TCP firewall 
    - listener port 51820
    - IP range 0.0.0.0/0
* Google DNS settings during bash install (8.8.8.8, 8.8.4.4) 

Everything good but can't visit Google sevice such as google drive, photo, account, gmail ... etc.

`Show Request Timeout`

Except google search (www.google.com) is working.

Any idea? thanks

**Comment by Nyr** [comment]
Not a problem with the script, ask Google,
