### ISSUE TITLE
Could support forward A IP to B IP?

### ISSUE THREAD

**Issue by akong77** [Nyr/wireguard-install#24]
My network like follow

`|Windows Wireguard VPN client(IP:10.8.0.2)|--->|A:Wireguard VPN Server(IP:10.8.0.1)|+|C:Wireguard VPN Client(IP:10.7.0.2)|--->|B:Wireguard Server(IP:10.7.0.1)|`

I can connect from Windows Wireguard VPN client to A wireguard vpn server and C wireguard client also can connect to B server.I hope windows client through A server and forward to B server then go to internet.But Windows only ping 10.8.0.0 network.I try setup C client allow ips add 10.8.0.0/24.But it's can't up this interface when I add allow ips 10.8.0.0/24.Could teach me how to do it?

**Comment by Nyr** [comment]
Sorry for the late response.

While possible, this is something out of the scope of this project.
