### ISSUE TITLE
Bandwith Settings

### ISSUE THREAD

**Issue by phyesix** [Nyr/wireguard-install#25]
Hi, is there any bandwidth option per user?

**Comment by ratijas** [comment]
As far as I can tell from WireGuard description, there's nothing like that in the core protocol, it's just a fast efficient tunnel with strong cryptography. You may look for 3rd party solutions though.

- https://old.reddit.com/r/WireGuard/comments/fii52f/data_traffic_limit_on_wireguard/
- https://old.reddit.com/r/WireGuard/comments/kawfh7/advicehelp_wireguard_traffic_shaping_data_limit/

I'm voting to close this issue.

**Comment by Nyr** [comment]
Thanks @ratijas, you are indeed right.
