### ISSUE TITLE
Cannot import .conf file in ubuntu

### ISSUE THREAD

**Issue by PrzemekSkw** [Nyr/wireguard-install#28]
I try to import in NetworkManager like .ovpn file from script but Ubuntu refuse to import wireguard client .conf file. Is there some special way to make it work?
Regards.

**Comment by TheBros35** [comment]
NetworkManager supports it, by using the command 

`nmcli connection import type wireguard file "$CONF_FILE"`

I don't believe that the Ubuntu GUI for importing config files will recognize a WireGuard config file, though. I believe it only handles OpenVPN.

**Comment by PrzemekSkw** [comment]
Thanks for help.
