### ISSUE TITLE
Can not access to internet

### ISSUE THREAD

**Issue by alexlii1971** [Nyr/wireguard-install#29]
Hello,

I am in China, and I already setup both server end and my PC client.

It show connected on client, but only show send data and no recieving data.

Once it is connected, I can not access any website on my pc.

I already tried all of the dns server for client:

1) Current system resolvers
   2) Google
   3) 1.1.1.1
   4) OpenDNS
   5) Quad9
   6) AdGuard

but no lucky to me, any suggestions would be highly appreciated.

Thanks and have a nice day.

**Comment by alexlii1971** [comment]
Sorry, I choose droplet in San Jose, it works now.

and just would like to check two points:

1# Ip forward already enabled please?
2# unbound unbound-host integrated?

To understand what I mean, please check at https://www.ckn.io/blog/2017/11/14/wireguard-vpn-typical-setup/

Thanks so much and have a nice day.

**Comment by Nyr** [comment]
> I am in China

This is the problem, VPN traffic is usually filtered by the GFW. If WireGuard is not working for you, try Shadowsocks instead.

> Ip forward already enabled please?

IP forwarding is indeed enabled.

> unbound unbound-host integrated?

Unbound is not installed by the script, external recursors are used instead.
