### ISSUE TITLE
debian_version is determined wrong

### ISSUE THREAD

**Issue by treeshateorcs** [Nyr/wireguard-install#3]
this is wrong

https://github.com/Nyr/wireguard-install/blob/137b08a8fb7f0f237a6a270232f000ef49d2f757/wireguard-install.sh#L34

my debian_version file only consists of "bullseye/sid", no numbers, i'm on the unstable branch of debian

**Comment by Nyr** [comment]
Unstable distributions are not officially supported and never will be, but this can be improved.

I'm keeping this issue open and will be addressed during the next few days. In the meantime you can of course override version check for the entire script changing the variable to `os_version="10"`.

**Comment by basedtho** [comment]
that's what i did
