### ISSUE TITLE
Webbased admin/user Gui?

### ISSUE THREAD

**Issue by alexlii1971** [Nyr/wireguard-install#30]
Hello,

This is not a issue post, but just a feature request.

Is it possible to intergrate an webased admin/user Gui please? 

Just like these ones:
https://github.com/perara/wg-manager#Showcase

[1]: https://github.com/Place1/wg-access-server

[2]: https://github.com/vx3r/wg-gen-web

[3]: https://github.com/EmbarkStudios/wg-ui

so that we can manager or add/remove user clients?

Thanks so much.

**Comment by Nyr** [comment]
No plans for that. The beauty of this project is to have a very lightweight and unobtrusive way to install and manage a WireGuard server, so setting up an entire web stack including Node.js is the antithesis of what I am trying to achieve.
