### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by kiprasmel** [Nyr/wireguard-install#34]
Hello, thanks for the great script. I was wondering -- would it be possible to have a docker container wrapper so that one could pull down a container in their server, start it up and get everything set up (perhaps some additional configs to route traffic from server to the container).

Thanks!

**Comment by Nyr** [comment]
Not planned. Since WireGuard is usually a kernel-level solution, Docker is not really useful here.

With that said, you can run this script inside a container and it will setup WireGuard using an user space tool (boringtun).
