### ISSUE TITLE
wg-iptables failed

### ISSUE THREAD

**Issue by youandri** [Nyr/wireguard-install#35]
Hello,

I try install this script on Ubuntu 20.04 with condition have installed docker with many IP local.
When i install this, script ask the IP and i choose IP Public.
Script running as well, except the wg-iptables service is failed.

When i look at the wg-iptables service, that command not include iptables path.
Example content created:
ExecStart= -t nat -A POSTROUTING -s 10.7.0.0/24 ! -d 10.7.0.0/24 -j SNAT --to [IP Public]

Not there iptables.

Any idea?

Thanks.

**Comment by Nyr** [comment]
Run ` iptables` and see if it is available.

Looks like iptables is not available in your system, which is weird because the script will install the iptables package if you are on Ubuntu and iptables or firewalld are not present.
