### ISSUE TITLE
QR Code not able to scan with UTF8

### ISSUE THREAD

**Issue by julianwue** [Nyr/wireguard-install#41]
Changed UTF8 to ASCII that I could scan the QR code in my MacOS Terminal. With the UTF8 there was to much space between the lines and no scanner could identify the data. Maybe you insert both options to generate - with a 1/2 selection or just both in sequence. 

```
qrencode -t UTF8 < ~/"$client.conf"
qrencode -t ASCII < ~/"$client.conf"
```

**Comment by spookiemulder** [comment]
use term instead of terminal

**Comment by Nyr** [comment]
Unable to reproduce.

![77f9c244-aaf5-438e-ad7e-ab94e670fd58](https://github.com/Nyr/wireguard-install/assets/739489/97e57c1c-3a1b-4c23-b665-41806a19e309)

![dde6d732-6c31-4fdd-a4e9-a69c96b0c910](https://github.com/Nyr/wireguard-install/assets/739489/2bf6a19e-1dd9-4018-bab2-03330c1879ea)
