### ISSUE TITLE
Building initial module for 4.19.0-16-amd64

### ISSUE THREAD

**Issue by SheikhTalal** [Nyr/wireguard-install#43]
The server is always hanging while installing the script on Building initial module for 4.19.0-16-amd64

**Comment by Nyr** [comment]
Well, I am going to need more than that if you want to troubleshoot the issue.

At the very least, provide the full installation log, say which distribution are you using (I assume it is Debian) and it would also be helpful to know what is your hosting provider and if this server is low on RAM.
