### ISSUE TITLE
[Feature Request] DoH / DoT support

### ISSUE THREAD

**Issue by Motophan** [Nyr/wireguard-install#45]
Feature request: add in the script an option to run Dns over Https or Dns over Tls to a trusted upstream provider (cloudflare, google, quad9, etc) 

You could install the bind the dns tunnel to a local address such as 127.53.53.53 where it would be unlikely to cause a port conflict and impossible to resolve dns requests outside the DoH/DoT tunnel.

This should fix https://github.com/Nyr/wireguard-install/issues/39

**Comment by Nyr** [comment]
This is best addressed client-side.

Also, it would not fix a DNS leak (which also needs to be addressed client-side).
