### ISSUE TITLE
uninstallation should fix networking the instalation broke (changed)

### ISSUE THREAD

**Issue by NESC1US** [Nyr/wireguard-install#47]
hi! when i installed the wireguard, my other interfaces were removed so i ended up without internet, when uninstalling this was kept so i lost my server, please set it so it restores old networking configuration.. thanks!

**Comment by trinib** [comment]
yes should have a reinstall option and keep clients

**Comment by Nyr** [comment]
The installer/uninstaller does not mess with network interfaces other than wg0, except for managing the NAT/firewall.

If you still think there is a problem, please give some steps to reproduce it. To start, which distribution are you using, and how specifically you think the networking was broken after removal.
