### ISSUE TITLE
Not really issue there 

### ISSUE THREAD

**Issue by malikshi** [Nyr/wireguard-install#5]
What's benefit using boringtun?

**Comment by malikshi** [comment]
and now become really an issue but a different problems.
>[Interface]
Address = 10.7.0.2/24
DNS = 1.1.1.1, 1.0.0.1
PrivateKey = sssssssssssssssssss
[Peer]
PublicKey = yyyyyyyyyyyyyyyyy
PresharedKey = xxxxxxxxxxxxxx
AllowedIPs = 0.0.0.0/0, ::/0
:443oint =
PersistentKeepalive = 25

any typo/wrong code here on the endpoint when creating clients

**Comment by malikshi** [comment]
the endpoint `ipaddress` , is it I'm doing the wrong step here? when asking for IP its already shown my public IP and I just `enter` it
>Do not alter the commented lines
They are used by wireguard-install
ENDPOINT 

I did fix it by adding my VPS IP address after ENDPOINT on server configuration.

**Comment by Nyr** [comment]
BoringTun is used because the WireGuard kernel module can't be set up from a container and an user space tool is required for that.

Thanks for the report, it was a nasty issue but it has now been fixed.
