### ISSUE TITLE
How to run multiple instances of the WireGuard server?

### ISSUE THREAD

**Issue by acrolink** [Nyr/wireguard-install#52]
Basically I want to create different VPN's each with it is own subnet and clients.

**Comment by acrolink** [comment]
I have managed to do that, I see that the configuration basically allows for that. Would be great if the script would allow doing something like this:

`wireguard-install.sh [server-name]`

And take care for assigning correct firewall rules and users for the different server configs. It is not that complicated I see. Some modifications to the script are needed.

Great work, thank you. As for my needs, I have already managed to make some multiple server setup but still some work on the automation of the script to adjust to the different server configurations.

**Comment by Nyr** [comment]
I am sorry, but I have no plans to implement this into the installer.
