### ISSUE TITLE
{Feature request} Ability to add custom IP to "Which IPv4 address should be used?"

### ISSUE THREAD

**Issue by geekafy** [Nyr/wireguard-install#55]
Hi! Tanks for the great script! I Installed it on a VPS today and noticed I was unable to specify a custom IP based on the fixed floating IP that the VPS was assigned. A floating IP if not assigned to the actual VPS  but simply redirected to the machine thus not detected. just thought it might be a nice addition. Thanks!

**Comment by Nyr** [comment]
Doesn't the VPS have a private IP address and the floating IP is provided via NAT there? If so, you need to select the private IP and then you will be asked for the public IP.

Which VPS provider are you using? I can take a look at their setup, but this the most common situation.
