### ISSUE TITLE
No internet after disconnect

### ISSUE THREAD

**Issue by PrzemekSkw** [Nyr/wireguard-install#60]
Hello, I have script installed on CentOS server. I have problem with laptops with Archlinux [KDE and GNOME] and Ubuntu. When I disconnect from wireguard in GUI (network manager) I don't have internet. I must disconnect from my wifi network and connect again. I import my wireguard to GUI with command: `nmcli connection import type wireguard file /etc/wireguard/wireguard.conf`.
Any advice how to fix that?
Regards.

**Comment by Nyr** [comment]
Client-side issue, so I am closing this.

I have zero experience with NetworkManager sorry.
