### ISSUE TITLE
Question: Updating

### ISSUE THREAD

**Issue by virtualos** [Nyr/wireguard-install#7]
Hello Nyr,

This is not a bug just a question: Do I have to uninstall and then reinstall wireguard script to get latest commits and fixes?

Thanks for the best OpenVPN and Wireguard brilliant and superb script in the world <3 <3 <3

**Comment by Nyr** [comment]
Thanks for the nice words.

Generally speaking, you should use the same version of the script during the entire life cycle of your installation. The script sets up WireGuard using repositories, and provides an automatic updater for those cases where repositories are not available.

So just upgrading your distribution like you normally do, WireGuard will be kept up to date.
