### ISSUE TITLE
no internet access after connect to wireguard

### ISSUE THREAD

**Issue by saelozahra** [Nyr/wireguard-install#70]
hello dears
i builded wireguard server with your script
and connected to android and windows client

but after connect to wireguard 
My internet connection was down
and  it say: no internet access

You may guide me ?

thanks alote

**Comment by KaeTuuN** [comment]
Hi @saelozahra,
we don't know anything about your setup, so it is nearly impossible to help you. Also this is not a Forum to get help from. ;)
But let me try to assist you a little.
First: Read everything carefully, understand it and then do something!

1. Is your Server connected to the Internet when wireguard is switched **off** at the server?
2. Is your Server connected to the Internet when wireguard is switched **on** at the server?
3. Is your Client connected to the Internet when wireguard is switched **off** at the client?
4. Is your Client connected to the Internet when wireguard is switched **on** at the Server and the client?
Some general Questions:
- Is Wireguard running correctly?
- Do Client and Server get the correct WG IP-Adresses?
- Is the configured DNS Server reachable?
- Check connections from Terminal/CMD ping command try to reach the Client/Server on success try to reach a Internetaddress by IP and by Name

If the answer is no at any of these steps, take a look at the wireguard and System logfiles. Read them, understand them, use a Searchengine you trust (I recommend DuckDuckGo) to get Explanations to Error Messages 

Greetings

**Comment by afzl-wtu** [comment]
I have installed wireguard with this script on OCI Ubuntu image. And working flawlessly. You just need to add Ingress rule for the port mention while installing.
Also check your firewall if it is not allowing the client to connect to internet

**Comment by Owned67** [comment]
Hello, im getting same...

1. yes
2.  no
3. yes
4. no


Wireguard running perfectly:
 ```
systemctl status wg-quick@wg0.service
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
     Loaded: loaded (/lib/systemd/system/wg-quick@.service; enabled; vendor preset: enabled)
     Active: active (exited) since Fri 2022-02-04 11:47:59 UTC; 40min ago
       Docs: man:wg-quick(8)
             man:wg(8)
             https://www.wireguard.com/
             https://www.wireguard.com/quickstart/
             https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
             https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
    Process: 19483 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=0/SUCCESS)
   Main PID: 19483 (code=exited, status=0/SUCCESS)

Feb 04 11:47:59 localhost systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
Feb 04 11:47:59 localhost wg-quick[19483]: [#] ip link add wg0 type wireguard
Feb 04 11:47:59 localhost wg-quick[19483]: [#] wg setconf wg0 /dev/fd/63
Feb 04 11:47:59 localhost wg-quick[19483]: [#] ip -4 address add XX.X.X.X/24 dev wg0
Feb 04 11:47:59 localhost wg-quick[19483]: [#] ip link set mtu 1420 up dev wg0
Feb 04 11:47:59 localhost systemd[1]: Finished WireGuard via wg-quick(8) for wg0.
```

Is the configured DNS Server reachable => yes for server and client is reachable

i can ping client from server but cannot ping server from client.

iptables -L -n
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:51820

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
ACCEPT     all  --  XX.X.X24          0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

It's a VPS with ubuntu 20.04

**Comment by masterwishx** [comment]
is it fixed ?

**Comment by afzl-wtu** [comment]
There are many issue with defaualt firewall ufw. It is better to un install it and then install firewalld. Please make sure firewalld is running by sudo systemctl status firewalld. then add rules there.

**Comment by afzl-wtu** [comment]
> Hello, im getting same...
> 
>     1. yes
> 
>     2. no
> 
>     3. yes
> 
>     4. no
> 
> 
> Wireguard running perfectly:
> 
> ```
> systemctl status wg-quick@wg0.service
> ● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
>     Loaded: loaded (/lib/systemd/system/wg-quick@.service; enabled; vendor preset: enabled)
>     Active: active (exited) since Fri 2022-02-04 11:47:59 UTC; 40min ago
>       Docs: man:wg-quick(8)
>             man:wg(8)
>             https://www.wireguard.com/
>             https://www.wireguard.com/quickstart/
>             https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
>             https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
>    Process: 19483 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=0/SUCCESS)
>   Main PID: 19483 (code=exited, status=0/SUCCESS)
> 
> Feb 04 11:47:59 localhost systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
> Feb 04 11:47:59 localhost wg-quick[19483]: [#] ip link add wg0 type wireguard
> Feb 04 11:47:59 localhost wg-quick[19483]: [#] wg setconf wg0 /dev/fd/63
> Feb 04 11:47:59 localhost wg-quick[19483]: [#] ip -4 address add XX.X.X.X/24 dev wg0
> Feb 04 11:47:59 localhost wg-quick[19483]: [#] ip link set mtu 1420 up dev wg0
> Feb 04 11:47:59 localhost systemd[1]: Finished WireGuard via wg-quick(8) for wg0.
> ```
> 
> Is the configured DNS Server reachable => yes for server and client is reachable
> 
> i can ping client from server but cannot ping server from client.
> 
> iptables -L -n
> 
> ```
> Chain INPUT (policy ACCEPT)
> target     prot opt source               destination
> ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:51820
> 
> Chain FORWARD (policy ACCEPT)
> target     prot opt source               destination
> ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
> ACCEPT     all  --  XX.X.X24          0.0.0.0/0
> ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
> ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
> 
> Chain OUTPUT (policy ACCEPT)
> target     prot opt source               destination
> ```
> 
> Client log:
> 
> ```
> 2022-02-04 13:36:44.512: [TUN] [Alpha] Handshake for peer 1 (IPVPS:51820) did not complete after 5 seconds, retrying (try 2)
> 2022-02-04 13:36:44.512: [TUN] [Alpha] Sending handshake initiation to peer 1 (IPVPS:51820)
> 2022-02-04 13:36:49.517: [TUN] [Alpha] Sending handshake initiation to peer 1 (IPVPS:51820)
> 2022-02-04 13:36:54.552: [TUN] [Alpha] Handshake for peer 1 (IPVPS:51820) did not complete after 5 seconds, retrying (try 2)
> ```
> 
> It's a VPS with ubuntu 20.04.
> 
> Ive found many post about his but cannot fix this...

read above comment. I am also using vps server of oracle with ubuntu 20.04. Do not forget to use firewalld and adding ingress rule

**Comment by Owned67** [comment]
I went through another solution ;) maybe i will retry soon with wireguard...

**Comment by masterwishx** [comment]
I'm not using firewall, ufw inactive, firewalld not installed.
Tryed 
1.argistan script
2. This script 
3. Pivpn
  But without inet access...
Then made new instance and installed argistan script again but no inet access. Then again made new instance and, 
The problem was in my case with Quad dns
9.9.9.9, 142.112.112.112 
No ping from oracle vps in Israel.
So changed to cloudflare 1.1.1.1
But now having very low speed 5Mbps /5Mbps
Instead of 50Mbps /50Mbps 
Maybe problem with mtu 9000?

**Comment by Nyr** [comment]
> The problem was in my case with Quad dns
> 9.9.9.9, 142.112.112.112
> No ping from oracle vps in Israel.
> So changed to cloudflare 1.1.1.1
> But now having very low speed 5Mbps /5Mbps
> Instead of 50Mbps /50Mbps
> Maybe problem with mtu 9000?

Indeed it seems like Quad9 is not reachable from some Israeli networks. I can not reach it from Anexia or G-Core Labs, but there is no problem from Bezeq or AS378.

About the speeds, maybe transit to your country is overcommitted, it likely has nothing to do with WireGuard.

I am closing this issue because it is not a problem with this project.

**Comment by masterwishx** [comment]
> 

I made vps in Israel becose I'm also in Israel.
Also I don't have any problems with QuadDNS
On HotNet provider....  It's best ping from it to me.
