### ISSUE TITLE
Can you add support for Oracle Linux?

### ISSUE THREAD

**Issue by myrust** [Nyr/wireguard-install#71]

**Comment by myrust** [comment]
> I have installed wireguard with this script on OCI Ubuntu image. And working flawlessly. You just need to add Ingress rule for the port mention while installing.

Oracle  Linux ≠ Ubuntu

**Comment by Jonnyan404** [comment]
> > I have installed wireguard with this script on OCI Ubuntu image. And working flawlessly. You just need to add Ingress rule for the port mention while installing.
> 
> Oracle Linux ≠ Ubuntu I know the script works for Ubuntu OS!

No, the author has already described it in the openvpn project.

**Comment by Nyr** [comment]
Given the uncertainty surrounding RHEL clones, I do not want to commit support for any which is not already supported.
