### ISSUE TITLE
Ubuntu is too old and unsupported

### ISSUE THREAD

**Issue by MrHumanRebel** [Nyr/wireguard-install#72]
My system:
Kernel: 5.4.0-96-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Xfce 4.16.0 
tk: Gtk 3.24.20 wm: xfwm4 dm: LightDM Distro: Linux Mint 20.3 Una
base: Ubuntu 20.04 focal 

What I did:

root@trade:~# wget https://git.io/wireguard -O wireguard-install.sh && bash wireguard-install.sh
--2022-01-24 16:53:56--  https://git.io/wireguard
Resolving git.io (git.io)... 18.205.36.100, 54.157.58.70, 54.162.128.250, ...
Connecting to git.io (git.io)|18.205.36.100|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Nyr/wireguard-install/master/wireguard-install.sh [following]
--2022-01-24 16:53:57--  https://raw.githubusercontent.com/Nyr/wireguard-install/master/wireguard-install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 29191 (29K) [text/plain]
Saving to: ‘wireguard-install.sh’

wireguard-install.s 100%[===================>]  28,51K  --.-KB/s    in 0,006s  

2022-01-24 16:53:58 (4,31 MB/s) - ‘wireguard-install.sh’ saved [29191/29191]

Ubuntu 18.04 or higher is required to use this installer.
This version of Ubuntu is too old and unsupported.

Thanks in advance!

**Comment by MrHumanRebel** [comment]
![git](https://user-images.githubusercontent.com/80947401/150817890-0329422f-fb23-4202-8d85-dcce7a3a8f0d.jpg)

**Comment by Nyr** [comment]
Mint is not supported, you can try overriding the check and setting distro to Ubuntu 20.04.
