### ISSUE TITLE
Feature Request: Option to specify different interface & client subnets

### ISSUE THREAD

**Issue by daryll-swer** [Nyr/wireguard-install#74]
It would be great to have an option in the script whereby for example:
```
We can specify WG0 interface subnet as:
IPv4: 10.0.0.0/24
IPv6: 2a10:6747:6::/64

Clients/Peers:
IPv4: 103.176.189.0/25
IPv6: Generated serially from 2a10:6747:6::/64
```

By using private IPs on WG0 interface for IPv4, we can make full use of a small public IPv4 subnet for each address as a /32 for each peer.

These methods work fine and I'm currently using a combination of this script and manual intervention to enter the /32 subnets and /64 serially.

It would be great if we can automate this using the script.

**Comment by Nyr** [comment]
I understand your use case, but to be honest it is unlikely to ever be implemented into the master branch.

Given IPv4 exhaustion, I am sure you understand that this is a niche feature and almost no one has its personal ASN and /24 like you do :)

I envy you a little bit.

**Comment by daryll-swer** [comment]
Some ISPs are also using your script and this can scale to the cloud for those who BYOIP as well. Would've been nice to have this option/feature in the script to ease automation.
