### ISSUE TITLE
After installation, there is no public key in the client and if we install it again, it looks like it has not been installed

### ISSUE THREAD

**Issue by danialvht** [Nyr/wireguard-install#75]
I have no idea what happened , it was working very well and want to make new client, when I run the script it looks like it has not been installed, and my old client not working ether , and now it complete the installation and make client but when I "cat" the .config there is no public key and its doesn't work. I try every thing on google searches, update upgrade reboot ... , do you have any idea?

**Comment by Nyr** [comment]
Try on a clean install and it will work. Some was clearly messed up at some point, but given the information provided it would be difficult to troubleshoot.
