### ISSUE TITLE
How to make it work while using CWP?

### ISSUE THREAD

**Issue by ItsAdventureTime** [Nyr/wireguard-install#76]
Hello,

I am currently using CWP (CentOS/Control Web Panel). And I would like to utilize my KVM VPS. That is why I wanted to install WireGuard in it. I noticed that WireGuard (this script) does not work anymore after installing CWP.

May I know if I need to open ports in iptables or something manually?

Thanks.

**Comment by Nyr** [comment]
Your panel is probably messing with the firewall.

You need to allow inbound connections on whatever port you choose for WireGuard (default is 51820) and postrouting from 10.7.0.0/24 and fddd:2c4:2c4:2c4::/64 to your public IP addresses.

For CentOS, the script usually employs firewalld to manage the routing. Make sure your web panel has not disabled it to set up something else.

**Comment by ItsAdventureTime** [comment]
> Your panel is probably messing with the firewall.
> 
> You need to allow inbound connections on whatever port you choose for WireGuard (default is 51820) and postrouting from 10.7.0.0/24 and fddd:2c4:2c4:2c4::/64 to your public IP addresses.
> 
> For CentOS, the script usually employs firewalld to manage the routing. Make sure your web panel has not disabled it to set up something else.

By the way I am using Alma Linux.
