### ISSUE TITLE
install line doesnt work (Temporary failure in name resolution)

### ISSUE THREAD

**Issue by Titanfinger** [Nyr/wireguard-install#77]
when i run:
wget https://git.io/wireguard -O wireguard-install.sh && bash wireguard-install.sh

This is the answer:
--2022-03-14 18:47:20--  https://git.io/wireguard
Resolving git.io (git.io)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'git.io'

Was the file location on github changed for "wireguard-install.sh" ?

Thanks for your help

**Comment by Nyr** [comment]
This is a DNS failure on your side.

Try this line instead:
`wget https://raw.githubusercontent.com/Nyr/wireguard-install/master/wireguard-install.sh -O wireguard-install.sh && bash wireguard-install.sh`

Or just download the script to your computer and upload to the server, but maybe you have a problem with the DNS resolver configured in your server.
