### ISSUE TITLE
Not Incrementing Correctly

### ISSUE THREAD

**Issue by aaronstuder** [Nyr/wireguard-install#8]
Just did a fresh install on Ubuntu 20.04.

The first client had the .2 IP address, however when I created a second client it also had .2

Third, and Forth clients got .3 and .4

Seems to be an issue during setup.

**Comment by Nyr** [comment]
Sorry, but can't reproduce this:

```
# cat first.conf | grep Address
Address = 10.7.0.2/24
# cat second.conf | grep Address
Address = 10.7.0.3/24
# cat third.conf | grep Address
Address = 10.7.0.4/24
```

I have also reviewed the offending code and can't find anything wrong.
