### ISSUE TITLE
Invalid QR-Code

### ISSUE THREAD

**Issue by maas0903** [Nyr/wireguard-install#89]
This repo sounded promising but unfortunately the QR-code to scan is not valid and it's not a road warrior type installation.
I expect a road warrior to be able to ping local resources and browse the internet.

Using From: iPhone
WireGuard Client version: 1.0.15 (26)
Server: Raspberry Pi 4
Server OS: BullsEye

**Comment by nisargvora** [comment]
Does your public endpoint IP/host name has "http://" prefixed?

I had the same invalid QR/file error on iOS because I was using full "http://www.<mysubdomain>.duckdns.org".
Removing "http://" and just keeping endpoint as "www.<mysubdomain>.duckdns.org" during script install generated valid QR.

**Comment by Nyr** [comment]
Please, provide a screenshot of the invalid QR code (and remove the client before publishing the screenshot).

There are some terminal apps where potentially the QR could be messed up, but this is rare.
