### ISSUE TITLE
Feature request / Question: Make the server also a "client" to a(n upstream VPN provider) wireguard server

### ISSUE THREAD

**Issue by vizion8-dan** [Nyr/wireguard-install#9]
Hi thanks for this awesome work! 

I currently think about how to possibily extend this by having the server on which I am running this script being itself a wireguard client to some upstream wireguard server? So in other words, the server sending all of its traffic only to another wireguard server. 

Thanks !

**Comment by Nyr** [comment]
This doesn't sound like a good idea if you are trying to "improve security" or something like that.

Anyway this is both a very niche option and one difficult to implement, so it's not going to happen, sorry.
