### ISSUE TITLE
Feature Request: Add option to specify IPv6 subnet

### ISSUE THREAD

**Issue by daryll-swer** [Nyr/wireguard-install#96]
At the moment, the script uses a hard-coded IPv6 subnet for the peers/clients. It would be great if it asks during install time (or even after) to specify your own /64 subnets.

In the case of Linode, we can get routed /64s or /56s, so if we enter a public /64 GUA, the script should also ask us “Do you want to use NAT66 or not?” as well.

**Comment by Nyr** [comment]
This would cause more problems than benefits as 90%+ ISPs do not provide fully routed subnets, there are more broken than proper IPv6 deployments, and most users do not understand that.

**Comment by daryll-swer** [comment]
@Nyr Your hard-coded ULA isn't helping, and it should permit the user to enter their own subnet of choice and NAT66 it or not.

I don't see how it would cause problems, your existing method however is:
https://blog.apnic.net/2022/05/16/ula-is-broken-in-dual-stack-networks/

**Comment by Nyr** [comment]
Most users of this installer do not understand what a fully routed IPv6 network is, or know if they have one available (a vast majority don't). Many users also do not understand what NAT is, its implications, or what is best for their use case.

Please do not tell me what I should do. Suggestions for improvement are welcome, but try to understand the full picture before of demanding changes.

I am open to suggestions if you have a better solution to seamlessly provide IPv6 connectivity from servers which have single /128s available, which sadly are the most common occurrence.

**Comment by daryll-swer** [comment]
The solution is crystal clear to me @Nyr. If anything, you seem to be rude/arrogant here. This will be my last comment, take it as you will. It looks like I'll just have to fork the script and change it myself.

Solution:
Your current method will be available for /128 (or whatever) users as is—So how are they hurt by the improvements?

Simply permit the subnet to be change-able, not to mention the **obvious** fact that ULAs are broken in dual-stack which is what 99% of the users would be behind, for which again, it would require the subnet to be adjustable from the installer's get go.

To begin with, I fail to see why you hard-coded a ULA block even for normal users who clearly wouldn't know about ULAs being ineffective on dual-stack.

**Comment by Nyr** [comment]
The current solution works everywhere, is simple and transparent for the user, and its real-world shortcomings are minimal. Also, there is nothing broken, perhaps it does not work as you wish it worked.

The prompt you proposed "Do you want to use NAT66 or not?" would be super confusing to many users, so I am not going to implement that.

Finally, this is not the first time that you are requesting or even demanding random stuff from me, including writing to my personal email, which I do not appreciate. Even then, I tried to help you, as you surely remember.

Anyway, in case someone else has something constructive to say about the technical matter, feel free to open a new issue.

**Comment by daryll-swer** [comment]
It seems you underestimate the power of documentation which is what would help end-users avoid confusion to begin with. And also seems you have never actually deployed IPv6 on a large scale and obtain direct feedback from customers/end-users.

People use work email IDs for non-personal (work) discussions. If you have a problem with that, then don't publish your work email in the public domain. I have hundreds of folks emailing me on a yearly basis asking for help (work) via my work email (in the public domain), and I never once shied away from helping them nor say “including writing to my personal email, which I do not appreciate”.

@Nyr “**Demanding**” isn't the same thing as requesting/asking, learn some internet etiquettes about communications.

Finally, you are behind an anonymous identity (in itself, which screams keyboard warrior), so I doubt I found your personal email. I assumed the email ID was work related, which was what the email conversation was about. I don't recall anything “personal” in the emails.

**Comment by KaeTuuN** [comment]
@daryll-swer  I have to say that I understand @Nyr 's point.
For less technical or Linux affine Users this script is easy to understand and easy to use. Today it is just 5 Clicks away to get your VPS and I doubt that vastly more than 90% of the script Users now, what a NAT66 is. Even I had to search for it, altough I'm working as an Admin for more then 15 years now.

Let me take this clear: Your wish seems helpful for large scale and professional Networks, but this is, as far as I would say, out of scope for this script. In my opinion it is for [SOHO](https://en.wikipedia.org/wiki/Small_office/home_office) Networks. If you want to use it on a larger scaled and more professional Network you should indeed fork it or buy some of Nyrs working time.
