### ISSUE TITLE
Create several user with one command

### ISSUE THREAD

**Issue by Jin33334** [Nyr/wireguard-install#98]
Hi,

Your script is simple, but it always works awesome.

I just want to use your script to create 20 in one time. Is there an possibility? I am not a coder why it is hard to do it myself. 

I have try, but its not working. 

wget https://git.io/wireguard -O wireguard-install.sh && bash wireguard-install.sh -1 -13 -3

Is there an possibility?

**Comment by Nyr** [comment]
Sorry but bulk operations are not supported at the moment.
