### ISSUE TITLE
Migrate from one server to another?

### ISSUE THREAD

**Issue by fracture-point** [Nyr/wireguard-install#99]
Love this script! I have been running this on a server for years, and would not like to migrate the entire config to a new server.

I ran the script on the new server, then copied the `/etc/wireguard/wg0.conf` file from the old server to the same location on the new server. I restarted the services / rebooted the new server, then took an old server's client connection file and updated it to the new server's IP.

The updated profile will not connect to the new server (it does not show any Data Received or Latest Handshake), and the new server does not show any client activity using `wg show`. 

`sudo systemctl status wg-quick@wg0.service` on the new server looks fine after a restart with the old server's config file:

```
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/usr/lib/systemd/system/wg-quick@.service; enabled; vendor preset: disabled)
   Active: active (exited) since Sat 2022-10-22 04:59:02 UTC; 14h ago
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
  Process: 244612 ExecStop=/usr/bin/wg-quick down wg0 (code=exited, status=0/SUCCESS)
  Process: 244642 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=0/SUCCESS)
 Main PID: 244642 (code=exited, status=0/SUCCESS)

Oct 22 04:59:02 masked systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
Oct 22 04:59:02 masked wg-quick[244642]: [#] ip link add wg0 type wireguard
Oct 22 04:59:02 masked wg-quick[244642]: [#] wg setconf wg0 /dev/fd/63
Oct 22 04:59:02 masked wg-quick[244642]: [#] ip -4 address add 10.7.0.1/24 dev wg0
Oct 22 04:59:02 masked wg-quick[244642]: [#] ip link set mtu 1420 up dev wg0
Oct 22 04:59:02 masked systemd[1]: Started WireGuard via wg-quick(8) for wg0.
```
Is there anything else that needs to be changed to make a migration work?

**Comment by Nyr** [comment]
All the WireGuard configuration is loaded form `wg0.conf`, and if you installed using the script, the rest of the system should be configured accordingly. So at first sight, it is difficult to tell what went wrong.
